package com.assessly.services;

import com.assessly.defs.RuleGenerationStatus;
import com.assessly.exceptions.RuleValidationException;
import com.assessly.models.RuleSet;
import com.assessly.repositories.interfaces.ControlRepository;
import com.assessly.repositories.interfaces.EvidenceRepository;
import com.assessly.repositories.interfaces.RuleSetRepository;
import com.assessly.services.interfaces.ApiKeySessionService;
import com.assessly.services.interfaces.DatasetService;
import com.assessly.services.interfaces.RuleService;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
public class RuleServiceImpl implements RuleService {
    private final DatasetService datasets;
    private final RuleSetRepository ruleSets;
    private final EvidenceRepository evidence;
    private final ControlRepository controls;
    private final ApiKeySessionService apiKeys;
    private final RuleEngine ruleEngine;

    public RuleServiceImpl(DatasetService datasets, RuleSetRepository ruleSets, EvidenceRepository evidence, ControlRepository controls, ApiKeySessionService apiKeys, RuleEngine ruleEngine) {
        this.datasets = datasets;
        this.ruleSets = ruleSets;
        this.evidence = evidence;
        this.controls = controls;
        this.apiKeys = apiKeys;
        this.ruleEngine = ruleEngine;
    }

    public RuleSet saveManual(UUID ownerId, UUID datasetId, String rulesJson, String summaryJson) {
        datasets.get(ownerId, datasetId);
        ruleEngine.validateRuleSet(rulesJson);
        RuleSet ruleSet = new RuleSet(datasetId, ruleSets.nextVersion(datasetId), RuleGenerationStatus.READY, rulesJson, blankSummary(summaryJson, "Manual Visual Rule Builder"));
        ruleSet.confirmExecutable();
        return ruleSets.save(ruleSet);
    }

    public RuleSet generate(UUID ownerId, UUID datasetId) {
        datasets.get(ownerId, datasetId);
        apiKeys.requireApiKey(ownerId);
        if (evidence.findByDataset(datasetId).isEmpty()) return cannot(datasetId, "Current Evidence is missing.");
        var docs = controls.findDocumentsByDataset(datasetId);
        if (docs.isEmpty()) return cannot(datasetId, "Security Control documents are missing.");

        String rulesJson = JsonSupport.write(Map.of("rules", List.of(Map.of(
                "id", "draft-rule-1",
                "fieldsUsed", List.of("role", "mfa_enabled"),
                "sourceControl", Map.of("controlId", "DEMO", "text", "Administrative accounts must use MFA."),
                "explanation", "Demo constrained AST generated by the PoC boundary. Replace with DeepSeek generated JSON after validation.",
                "ast", Map.of(
                        "type", "if",
                        "if", Map.of("type", "condition", "field", "role", "operator", "=", "value", "admin"),
                        "then", Map.of("type", "condition", "field", "mfa_enabled", "operator", "=", "value", true)
                )
        ))));
        try {
            ruleEngine.validateRuleSet(rulesJson);
            RuleSet ruleSet = new RuleSet(datasetId, ruleSets.nextVersion(datasetId), RuleGenerationStatus.READY, rulesJson, JsonSupport.write(Map.of("status", "READY", "note", "DeepSeek integration boundary validated; current PoC emits a constrained demo rule.")));
            return ruleSets.save(ruleSet);
        } catch (RuleValidationException e) {
            return ruleSets.save(new RuleSet(datasetId, ruleSets.nextVersion(datasetId), RuleGenerationStatus.ERROR, "{\"rules\":[]}", JsonSupport.write(Map.of("reason", e.getMessage()))));
        }
    }

    public RuleSet confirm(UUID ownerId, UUID datasetId, UUID ruleSetId) {
        datasets.get(ownerId, datasetId);
        RuleSet ruleSet = ruleSets.findByIdAndDataset(ruleSetId, datasetId).orElseThrow();
        ruleSet.confirmExecutable();
        return ruleSets.save(ruleSet);
    }

    public List<RuleSet> list(UUID ownerId, UUID datasetId) {
        datasets.get(ownerId, datasetId);
        return ruleSets.findAllByDataset(datasetId);
    }

    private RuleSet cannot(UUID datasetId, String reason) {
        return ruleSets.save(new RuleSet(datasetId, ruleSets.nextVersion(datasetId), RuleGenerationStatus.CANNOT_AUTOMATE, "{\"rules\":[]}", JsonSupport.write(Map.of("reason", reason))));
    }

    private String blankSummary(String summaryJson, String source) {
        return summaryJson == null || summaryJson.isBlank() ? JsonSupport.write(Map.of("source", source)) : summaryJson;
    }
}
